POST http://localhost:3000/register HTTP/1.1
content-Type: application/json

{
  "username": "aaravdev",
  "password": "a123",
  "email": "aarav@example.com",
  "name": "Aarav Sharma"
}

###

POST http://localhost:3000/login HTTP/1.1
content-Type: application/json

{
  "email": "aarav@example.com",
  "password": "a123"    
}

###
GET http://localhost:3000/get_user_and_profile
Content-Type: application/json

{
  "token": "f8d35441f5d1f6a24ab1cb763c9e0ecd1ae34413bef678a37909f0e0c094cb2c"
}

###
POST http://localhost:3000/update_profile_data
Content-Type: application/json

{
  "token": "f8d35441f5d1f6a24ab1cb763c9e0ecd1ae34413bef678a37909f0e0c094cb2c",
   "bio": "Backend engineer focused on scalable APIs, cloud infrastructure, and clean architecture.",
      "currentPost": "Backend Engineer at Nexora Tech",
      "pastWork": [
        {
          "company": "CloudByte Systems",
          "position": "Node.js Developer",
          "years": "2023 - 2025"  
        },
        {
          "company": "DevStack Labs",
          "position": "Software Engineering Intern",
          "years": "2022 - 2023"
        }
      ],
      "education": [
        {
          "school": "Indian Institute of Technology Delhi",
          "degree": "B.Tech in Information Technology",
          "fieldOfStudy": "2021 - 2025"
        }
      ]
}

###
GET http://localhost:3000/user/get_all_users
